import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export interface AnalysisResult {
  exerciseName: string;
  formAccuracy: number;
  balanceScore: number;
  depthConsistency: number;
  improvementTrend: number;
  totalSessions: number;
  averageScore: number;
  personalBest: number;
  consistency: number;
  timestamp: Date;
}

export async function generateAnalysisReport(
  data: AnalysisResult
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4 size
  const { width, height } = page.getSize();

  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesRomanBoldFont = await pdfDoc.embedFont(
    StandardFonts.TimesRomanBold
  );
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBoldFont = await pdfDoc.embedFont(
    StandardFonts.HelveticaBold
  );

  // Header
  page.drawText("SPORTS PERFORMANCE ANALYSIS REPORT", {
    x: 50,
    y: height - 50,
    size: 24,
    font: timesRomanBoldFont,
    color: rgb(0, 0.2, 0.4),
  });

  // Date and Exercise Info
  let yPosition = height - 100;
  page.drawText(`Exercise: ${data.exerciseName}`, {
    x: 50,
    y: yPosition,
    size: 14,
    font: helveticaBoldFont,
    color: rgb(0, 0, 0),
  });

  yPosition -= 25;
  page.drawText(
    `Report Date: ${data.timestamp.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`,
    {
      x: 50,
      y: yPosition,
      size: 12,
      font: helveticaFont,
      color: rgb(0.3, 0.3, 0.3),
    }
  );

  // Form Analysis Section
  yPosition -= 50;
  page.drawText("FORM ANALYSIS", {
    x: 50,
    y: yPosition,
    size: 14,
    font: helveticaBoldFont,
    color: rgb(0, 0.2, 0.4),
  });

  yPosition -= 30;
  const metrics = [
    { label: "Form Accuracy", value: data.formAccuracy },
    { label: "Balance Score", value: data.balanceScore },
    { label: "Depth Consistency", value: data.depthConsistency },
  ];

  metrics.forEach((metric) => {
    page.drawText(`${metric.label}:`, {
      x: 70,
      y: yPosition,
      size: 11,
      font: helveticaBoldFont,
      color: rgb(0, 0, 0),
    });

    page.drawText(`${metric.value}%`, {
      x: 300,
      y: yPosition,
      size: 11,
      font: helveticaBoldFont,
      color: rgb(0, 0.6, 0.8),
    });

    // Draw progress bar
    const barWidth = 150;
    const barHeight = 8;
    page.drawRectangle({
      x: 350,
      y: yPosition - 2,
      width: barWidth,
      height: barHeight,
      borderColor: rgb(0.8, 0.8, 0.8),
      borderWidth: 1,
    });

    page.drawRectangle({
      x: 350,
      y: yPosition - 2,
      width: (barWidth * metric.value) / 100,
      height: barHeight,
      color: rgb(0, 0.6, 0.8),
    });

    yPosition -= 25;
  });

  // Performance Summary Section
  yPosition -= 30;
  page.drawText("PERFORMANCE SUMMARY", {
    x: 50,
    y: yPosition,
    size: 14,
    font: helveticaBoldFont,
    color: rgb(0, 0.2, 0.4),
  });

  yPosition -= 30;
  const summaryMetrics = [
    { label: "Total Sessions", value: `${data.totalSessions}` },
    { label: "Average Score", value: `${data.averageScore}%` },
    { label: "Personal Best", value: `${data.personalBest}%` },
    { label: "Consistency", value: `${data.consistency}%` },
    { label: "Improvement Trend", value: `+${data.improvementTrend}%` },
  ];

  summaryMetrics.forEach((metric) => {
    page.drawText(`${metric.label}:`, {
      x: 70,
      y: yPosition,
      size: 11,
      font: helveticaFont,
      color: rgb(0, 0, 0),
    });

    page.drawText(metric.value, {
      x: 300,
      y: yPosition,
      size: 11,
      font: helveticaBoldFont,
      color: rgb(0, 0.4, 0.8),
    });

    yPosition -= 20;
  });

  // Recommendations Section
  yPosition -= 30;
  page.drawText("RECOMMENDATIONS", {
    x: 50,
    y: yPosition,
    size: 14,
    font: helveticaBoldFont,
    color: rgb(0, 0.2, 0.4),
  });

  yPosition -= 25;
  const recommendations = [
    "• Continue practicing with focus on form accuracy",
    "• Work on balance and stability during movements",
    "• Maintain consistency in training sessions",
    "• Track progress weekly to monitor improvements",
  ];

  recommendations.forEach((rec) => {
    page.drawText(rec, {
      x: 70,
      y: yPosition,
      size: 10,
      font: helveticaFont,
      color: rgb(0.2, 0.2, 0.2),
    });
    yPosition -= 18;
  });

  // Footer
  page.drawText("Generated by WazenAI - Sports Performance Analysis System", {
    x: 50,
    y: 30,
    size: 9,
    font: helveticaFont,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
