import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar" | "es" | "fr" | "de" | "zh";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    "nav.home": "Home",
    "nav.demo": "Demo",
    "nav.dashboard": "Dashboard",
    "nav.analysis": "Analysis",
    "nav.settings": "Settings",
    "home.title": "Analyze Your Form, Improve Performance",
    "home.subtitle": "AI-powered analysis with real-time corrections",
    "home.startAnalysis": "Start Analysis",
    "home.demo": "Demo",
    "home.progress": "Your Progress",
    "home.sessions": "Sessions",
    "home.exercises": "Exercises",
    "home.score": "Score",
    "home.streak": "Day Streak",
    "settings.account": "Account Settings",
    "settings.subscription": "Subscription",
    "settings.notifications": "Notifications",
    "settings.preferences": "Preferences",
    "settings.darkMode": "Dark Mode",
    "settings.language": "Language",
    "settings.autoLanguage": "Auto-detect",
    "settings.voice": "Voice",
    "settings.save": "Save",
    "settings.cancel": "Cancel",
    "dashboard.totalSessions": "Total Sessions",
    "dashboard.totalExercises": "Total Exercises",
    "dashboard.avgScore": "Average Score",
    "dashboard.currentStreak": "Current Streak",
    "dashboard.days": "days",
    "dashboard.recentAnalysis": "Recent Analysis",
    "dashboard.noAnalysis": "No analysis yet. Start your first analysis!",
    "demo.welcome": "Welcome to WazenAI",
    "demo.learnHow": "Learn how to use our intelligent fitness analysis system",
    "demo.sixSteps": "6 Simple Steps",
    "demo.keyFeatures": "Key Features",
    "demo.exerciseDemos": "22 Exercise Demonstrations",
    "demo.readyToStart": "Ready to Get Started?",
    "demo.experience": "Experience AI-powered fitness analysis in real-time",
    "demo.step1": "Enable Camera",
    "demo.step1Desc": "Allow the app to access your camera for real-time analysis",
    "demo.step2": "Select Exercise",
    "demo.step2Desc": "Choose from 22 different exercises (Squat, Deadlift, Bench Press, etc.)",
    "demo.step3": "Perform Movement",
    "demo.step3Desc": "Execute the exercise while the AI analyzes your form",
    "demo.step4": "Get Feedback",
    "demo.step4Desc": "Receive real-time corrections and tips to improve your form",
    "demo.step5": "View Report",
    "demo.step5Desc": "See detailed analysis with scores, angles, and improvement areas",
    "demo.step6": "Track Progress",
    "demo.step6Desc": "Monitor your improvements over time in the dashboard",
    "demo.feature1": "Real-time Analysis",
    "demo.feature1Desc": "Instant feedback on your form during exercise",
    "demo.feature2": "22 Exercises",
    "demo.feature2Desc": "Support for common gym exercises",
    "demo.feature3": "AI Corrections",
    "demo.feature3Desc": "Smart suggestions to prevent injuries",
    "demo.feature4": "Progress Tracking",
    "demo.feature4Desc": "Monitor your improvements over time",
    "demo.feature5": "Detailed Reports",
    "demo.feature5Desc": "Comprehensive analysis with metrics",
    "demo.feature6": "Community Chat",
    "demo.feature6Desc": "Connect with other fitness enthusiasts",
    "exercise.barbellBicepsCurl": "Barbell Biceps Curl",
    "exercise.benchPress": "Bench Press",
    "exercise.chestFlyMachine": "Chest Fly Machine",
    "exercise.deadlift": "Deadlift",
    "exercise.declineBenchPress": "Decline Bench Press",
    "exercise.hammerCurl": "Hammer Curl",
    "exercise.hipThrust": "Hip Thrust",
    "exercise.inclineBenchPress": "Incline Bench Press",
    "exercise.latPulldown": "Lat Pulldown",
    "exercise.lateralRaise": "Lateral Raise",
    "exercise.legExtension": "Leg Extension",
    "exercise.legRaises": "Leg Raises",
    "exercise.plank": "Plank",
    "exercise.pullUp": "Pull Up",
    "exercise.pushUp": "Push-up",
    "exercise.romanianDeadlift": "Romanian Deadlift",
    "exercise.russianTwist": "Russian Twist",
    "exercise.shoulderPress": "Shoulder Press",
    "exercise.squat": "Squat",
    "exercise.tBarRow": "T Bar Row",
    "exercise.tricepPushdown": "Tricep Pushdown",
    "exercise.tricepDips": "Tricep Dips",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.demo": "عرض توضيحي",
    "nav.dashboard": "لوحة التحكم",
    "nav.analysis": "التحليل",
    "nav.settings": "الإعدادات",
    "home.title": "حلل شكلك، حسّن أدائك",
    "home.subtitle": "تحليل مدعوم بالذكاء الاصطناعي مع تصحيحات في الوقت الفعلي",
    "home.startAnalysis": "ابدأ التحليل",
    "home.demo": "عرض توضيحي",
    "home.progress": "تقدمك",
    "home.sessions": "الجلسات",
    "home.exercises": "التمارين",
    "home.score": "النقاط",
    "home.streak": "سلسلة الأيام",
    "settings.account": "إعدادات الحساب",
    "settings.subscription": "الاشتراك",
    "settings.notifications": "الإخطارات",
    "settings.preferences": "التفضيلات",
    "settings.darkMode": "الوضع الليلي",
    "settings.language": "اللغة",
    "settings.autoLanguage": "كشف تلقائي",
    "settings.voice": "الصوت",
    "settings.save": "حفظ",
    "settings.cancel": "إلغاء",
    "dashboard.totalSessions": "إجمالي الجلسات",
    "dashboard.totalExercises": "إجمالي التمارين",
    "dashboard.avgScore": "متوسط النقاط",
    "dashboard.currentStreak": "الأيام المتتالية",
    "dashboard.days": "أيام",
    "dashboard.recentAnalysis": "التحليلات الأخيرة",
    "dashboard.noAnalysis": "لا توجد تحليلات بعد. ابدأ تحليلك الأول!",
    "demo.welcome": "مرحباً بك في WazenAI",
    "demo.learnHow": "تعرف على كيفية استخدام نظام تحليل اللياقة الذكي",
    "demo.sixSteps": "6 خطوات بسيطة",
    "demo.keyFeatures": "الميزات الرئيسية",
    "demo.exerciseDemos": "22 عرض توضيحي للتمارين",
    "demo.readyToStart": "هل أنت مستعد للبدء؟",
    "demo.experience": "جرب تحليل اللياقة المدعوم بالذكاء الاصطناعي في الوقت الفعلي",
    "demo.step1": "تفعيل الكاميرا",
    "demo.step1Desc": "السماح للتطبيق بالوصول إلى الكاميرا للتحليل في الوقت الفعلي",
    "demo.step2": "اختر التمرين",
    "demo.step2Desc": "اختر من بين 22 تمرينًا مختلفًا (القرفصاء، الرفعة المميتة، ضغط البنش، إلخ)",
    "demo.step3": "تنفيذ الحركة",
    "demo.step3Desc": "قم بتنفيذ التمرين بينما تحلل الذكاء الاصطناعي شكلك",
    "demo.step4": "احصل على التعليقات",
    "demo.step4Desc": "احصل على تصحيحات في الوقت الفعلي ونصائح لتحسين شكلك",
    "demo.step5": "عرض التقرير",
    "demo.step5Desc": "شاهد تحليلاً مفصلاً مع النقاط والزوايا ومناطق التحسين",
    "demo.step6": "تتبع التقدم",
    "demo.step6Desc": "راقب تحسنك بمرور الوقت في لوحة التحكم",
    "demo.feature1": "التحليل في الوقت الفعلي",
    "demo.feature1Desc": "ملاحظات فورية حول شكلك أثناء التمرين",
    "demo.feature2": "22 تمرينًا",
    "demo.feature2Desc": "دعم تمارين الجيم الشائعة",
    "demo.feature3": "تصحيحات الذكاء الاصطناعي",
    "demo.feature3Desc": "اقتراحات ذكية لمنع الإصابات",
    "demo.feature4": "تتبع التقدم",
    "demo.feature4Desc": "راقب تحسنك بمرور الوقت",
    "demo.feature5": "تقارير مفصلة",
    "demo.feature5Desc": "تحليل شامل مع المقاييس",
    "demo.feature6": "دردشة المجتمع",
    "demo.feature6Desc": "تواصل مع عشاق اللياقة الآخرين",
    "exercise.barbellBicepsCurl": "تجعيد البايسبس بالدمبل",
    "exercise.benchPress": "ضغط البنش",
    "exercise.chestFlyMachine": "آلة الصدر الطائرة",
    "exercise.deadlift": "الرفعة المميتة",
    "exercise.declineBenchPress": "ضغط البنش المنخفض",
    "exercise.hammerCurl": "تجعيد المطرقة",
    "exercise.hipThrust": "دفع الورك",
    "exercise.inclineBenchPress": "ضغط البنش المرتفع",
    "exercise.latPulldown": "سحب العضلة الظهرية",
    "exercise.lateralRaise": "رفع جانبي",
    "exercise.legExtension": "تمديد الساق",
    "exercise.legRaises": "رفع الساق",
    "exercise.plank": "لوح الجسم",
    "exercise.pullUp": "السحب للأعلى",
    "exercise.pushUp": "تمرين الضغط",
    "exercise.romanianDeadlift": "الرفعة المميتة الرومانية",
    "exercise.russianTwist": "الالتواء الروسي",
    "exercise.shoulderPress": "ضغط الكتف",
    "exercise.squat": "القرفصاء",
    "exercise.tBarRow": "صف T-Bar",
    "exercise.tricepPushdown": "دفع التراي سيبس",
    "exercise.tricepDips": "غطسات التراي سيبس",
  },
  es: {
    "nav.home": "Inicio",
    "nav.demo": "Demo",
    "nav.dashboard": "Panel de Control",
    "nav.analysis": "Análisis",
    "nav.settings": "Configuración",
    "home.title": "Analiza tu Forma, Mejora tu Desempeño",
    "home.subtitle": "Análisis impulsado por IA con correcciones en tiempo real",
    "home.startAnalysis": "Comenzar Análisis",
    "home.demo": "Demo",
    "home.progress": "Tu Progreso",
    "home.sessions": "Sesiones",
    "home.exercises": "Ejercicios",
    "home.score": "Puntuación",
    "home.streak": "Racha de Días",
    "settings.account": "Configuración de Cuenta",
    "settings.subscription": "Suscripción",
    "settings.notifications": "Notificaciones",
    "settings.preferences": "Preferencias",
    "settings.darkMode": "Modo Oscuro",
    "settings.language": "Idioma",
    "settings.autoLanguage": "Detección Automática",
    "settings.voice": "Voz",
    "settings.save": "Guardar",
    "settings.cancel": "Cancelar",
    "dashboard.totalSessions": "Sesiones Totales",
    "dashboard.totalExercises": "Ejercicios Totales",
    "dashboard.avgScore": "Puntuación Promedio",
    "dashboard.currentStreak": "Racha Actual",
    "dashboard.days": "días",
    "dashboard.recentAnalysis": "Análisis Recientes",
    "dashboard.noAnalysis": "Sin análisis aún. ¡Comienza tu primer análisis!",
    "demo.welcome": "Bienvenido a WazenAI",
    "demo.learnHow": "Aprende cómo usar nuestro sistema inteligente de análisis de fitness",
    "demo.sixSteps": "6 Pasos Simples",
    "demo.keyFeatures": "Características Clave",
    "demo.exerciseDemos": "22 Demostraciones de Ejercicios",
    "demo.readyToStart": "¿Listo para Comenzar?",
    "demo.experience": "Experimenta análisis de fitness impulsado por IA en tiempo real",
    "demo.step1": "Habilitar Cámara",
    "demo.step1Desc": "Permite que la aplicación acceda a tu cámara para análisis en tiempo real",
    "demo.step2": "Seleccionar Ejercicio",
    "demo.step2Desc": "Elige entre 22 ejercicios diferentes (Sentadilla, Peso Muerto, Press de Banca, etc.)",
    "demo.step3": "Realizar Movimiento",
    "demo.step3Desc": "Ejecuta el ejercicio mientras la IA analiza tu forma",
    "demo.step4": "Obtener Retroalimentación",
    "demo.step4Desc": "Recibe correcciones en tiempo real y consejos para mejorar tu forma",
    "demo.step5": "Ver Informe",
    "demo.step5Desc": "Consulta análisis detallado con puntuaciones, ángulos y áreas de mejora",
    "demo.step6": "Rastrear Progreso",
    "demo.step6Desc": "Monitorea tus mejoras a lo largo del tiempo en el panel",
    "demo.feature1": "Análisis en Tiempo Real",
    "demo.feature1Desc": "Retroalimentación instantánea sobre tu forma durante el ejercicio",
    "demo.feature2": "22 Ejercicios",
    "demo.feature2Desc": "Soporte para ejercicios comunes de gimnasio",
    "demo.feature3": "Correcciones IA",
    "demo.feature3Desc": "Sugerencias inteligentes para prevenir lesiones",
    "demo.feature4": "Rastreo de Progreso",
    "demo.feature4Desc": "Monitorea tus mejoras a lo largo del tiempo",
    "demo.feature5": "Informes Detallados",
    "demo.feature5Desc": "Análisis completo con métricas",
    "demo.feature6": "Chat Comunitario",
    "demo.feature6Desc": "Conecta con otros entusiastas del fitness",
    "exercise.barbellBicepsCurl": "Curl de Bíceps con Barra",
    "exercise.benchPress": "Press de Banca",
    "exercise.chestFlyMachine": "Máquina de Aperturas de Pecho",
    "exercise.deadlift": "Peso Muerto",
    "exercise.declineBenchPress": "Press de Banca Declinado",
    "exercise.hammerCurl": "Curl Martillo",
    "exercise.hipThrust": "Empuje de Cadera",
    "exercise.inclineBenchPress": "Press de Banca Inclinado",
    "exercise.latPulldown": "Jalón Dorsal",
    "exercise.lateralRaise": "Elevación Lateral",
    "exercise.legExtension": "Extensión de Pierna",
    "exercise.legRaises": "Elevaciones de Pierna",
    "exercise.plank": "Plancha",
    "exercise.pullUp": "Dominada",
    "exercise.pushUp": "Flexión",
    "exercise.romanianDeadlift": "Peso Muerto Rumano",
    "exercise.russianTwist": "Giro Ruso",
    "exercise.shoulderPress": "Press de Hombro",
    "exercise.squat": "Sentadilla",
    "exercise.tBarRow": "Remo T-Bar",
    "exercise.tricepPushdown": "Extensión de Tríceps",
    "exercise.tricepDips": "Fondos de Tríceps",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.demo": "Démo",
    "nav.dashboard": "Tableau de Bord",
    "nav.analysis": "Analyse",
    "nav.settings": "Paramètres",
    "home.title": "Analysez votre Forme, Améliorez votre Performance",
    "home.subtitle": "Analyse alimentée par l'IA avec corrections en temps réel",
    "home.startAnalysis": "Commencer l'Analyse",
    "home.demo": "Démo",
    "home.progress": "Votre Progression",
    "home.sessions": "Séances",
    "home.exercises": "Exercices",
    "home.score": "Score",
    "home.streak": "Série de Jours",
    "settings.account": "Paramètres du Compte",
    "settings.subscription": "Abonnement",
    "settings.notifications": "Notifications",
    "settings.preferences": "Préférences",
    "settings.darkMode": "Mode Sombre",
    "settings.language": "Langue",
    "settings.autoLanguage": "Détection Automatique",
    "settings.voice": "Voix",
    "settings.save": "Enregistrer",
    "settings.cancel": "Annuler",
    "dashboard.totalSessions": "Sessions Totales",
    "dashboard.totalExercises": "Exercices Totaux",
    "dashboard.avgScore": "Score Moyen",
    "dashboard.currentStreak": "Série Actuelle",
    "dashboard.days": "jours",
    "dashboard.recentAnalysis": "Analyses Récentes",
    "dashboard.noAnalysis": "Pas d'analyse encore. Commencez votre première analyse!",
    "demo.welcome": "Bienvenue dans WazenAI",
    "demo.learnHow": "Découvrez comment utiliser notre système intelligent d'analyse de fitness",
    "demo.sixSteps": "6 Étapes Simples",
    "demo.keyFeatures": "Caractéristiques Clés",
    "demo.exerciseDemos": "22 Démonstrations d'Exercices",
    "demo.readyToStart": "Prêt à Commencer?",
    "demo.experience": "Expérimentez l'analyse de fitness alimentée par l'IA en temps réel",
    "demo.step1": "Activer la Caméra",
    "demo.step1Desc": "Autorisez l'application à accéder à votre caméra pour une analyse en temps réel",
    "demo.step2": "Sélectionner un Exercice",
    "demo.step2Desc": "Choisissez parmi 22 exercices différents (Squat, Soulevé de Terre, Développé Couché, etc.)",
    "demo.step3": "Effectuer le Mouvement",
    "demo.step3Desc": "Exécutez l'exercice pendant que l'IA analyse votre forme",
    "demo.step4": "Obtenir des Commentaires",
    "demo.step4Desc": "Recevez des corrections en temps réel et des conseils pour améliorer votre forme",
    "demo.step5": "Voir le Rapport",
    "demo.step5Desc": "Consultez une analyse détaillée avec les scores, les angles et les domaines d'amélioration",
    "demo.step6": "Suivre la Progression",
    "demo.step6Desc": "Surveillez vos améliorations au fil du temps dans le tableau de bord",
    "demo.feature1": "Analyse en Temps Réel",
    "demo.feature1Desc": "Retours instantanés sur votre forme pendant l'exercice",
    "demo.feature2": "22 Exercices",
    "demo.feature2Desc": "Support pour les exercices de salle de sport courants",
    "demo.feature3": "Corrections IA",
    "demo.feature3Desc": "Suggestions intelligentes pour prévenir les blessures",
    "demo.feature4": "Suivi de la Progression",
    "demo.feature4Desc": "Surveillez vos améliorations au fil du temps",
    "demo.feature5": "Rapports Détaillés",
    "demo.feature5Desc": "Analyse complète avec des métriques",
    "demo.feature6": "Chat Communautaire",
    "demo.feature6Desc": "Connectez-vous avec d'autres passionnés de fitness",
    "exercise.barbellBicepsCurl": "Curl Haltères Biceps",
    "exercise.benchPress": "Développé Couché",
    "exercise.chestFlyMachine": "Machine Écartés Pectoraux",
    "exercise.deadlift": "Soulevé de Terre",
    "exercise.declineBenchPress": "Développé Couché Décliné",
    "exercise.hammerCurl": "Curl Marteau",
    "exercise.hipThrust": "Poussée de Hanche",
    "exercise.inclineBenchPress": "Développé Couché Incliné",
    "exercise.latPulldown": "Tirage Lat",
    "exercise.lateralRaise": "Élévation Latérale",
    "exercise.legExtension": "Extension de Jambe",
    "exercise.legRaises": "Levées de Jambe",
    "exercise.plank": "Planche",
    "exercise.pullUp": "Tractions",
    "exercise.pushUp": "Pompe",
    "exercise.romanianDeadlift": "Soulevé de Terre Roumain",
    "exercise.russianTwist": "Rotation Russe",
    "exercise.shoulderPress": "Développé Épaules",
    "exercise.squat": "Squat",
    "exercise.tBarRow": "Tirage T-Bar",
    "exercise.tricepPushdown": "Poussée Triceps",
    "exercise.tricepDips": "Dips Triceps",
  },
  de: {
    "nav.home": "Startseite",
    "nav.demo": "Demo",
    "nav.dashboard": "Dashboard",
    "nav.analysis": "Analyse",
    "nav.settings": "Einstellungen",
    "home.title": "Analysiere deine Form, verbessere deine Leistung",
    "home.subtitle": "KI-gestützte Analyse mit Echtzeit-Korrektionen",
    "home.startAnalysis": "Analyse starten",
    "home.demo": "Demo",
    "home.progress": "Dein Fortschritt",
    "home.sessions": "Sitzungen",
    "home.exercises": "Übungen",
    "home.score": "Punktzahl",
    "home.streak": "Tage-Serie",
    "settings.account": "Kontoeinstellungen",
    "settings.subscription": "Abonnement",
    "settings.notifications": "Benachrichtigungen",
    "settings.preferences": "Einstellungen",
    "settings.darkMode": "Dunkler Modus",
    "settings.language": "Sprache",
    "settings.autoLanguage": "Automatische Erkennung",
    "settings.voice": "Stimme",
    "settings.save": "Speichern",
    "settings.cancel": "Abbrechen",
    "dashboard.totalSessions": "Gesamtsitzungen",
    "dashboard.totalExercises": "Gesamtübungen",
    "dashboard.avgScore": "Durchschnittliche Punktzahl",
    "dashboard.currentStreak": "Aktuelle Serie",
    "dashboard.days": "Tage",
    "dashboard.recentAnalysis": "Aktuelle Analysen",
    "dashboard.noAnalysis": "Noch keine Analyse. Starten Sie Ihre erste Analyse!",
    "demo.welcome": "Willkommen bei WazenAI",
    "demo.learnHow": "Erfahren Sie, wie Sie unser intelligentes Fitness-Analysesystem nutzen",
    "demo.sixSteps": "6 Einfache Schritte",
    "demo.keyFeatures": "Wichtigste Funktionen",
    "demo.exerciseDemos": "22 Übungsdemonstationen",
    "demo.readyToStart": "Bereit zum Starten?",
    "demo.experience": "Erleben Sie KI-gestützte Fitness-Analyse in Echtzeit",
    "demo.step1": "Kamera Aktivieren",
    "demo.step1Desc": "Erlauben Sie der App, auf Ihre Kamera für Echtzeit-Analyse zuzugreifen",
    "demo.step2": "Übung Auswählen",
    "demo.step2Desc": "Wählen Sie aus 22 verschiedenen Übungen (Kniebeuge, Kreuzheben, Bankdrücken, etc.)",
    "demo.step3": "Bewegung Ausführen",
    "demo.step3Desc": "Führen Sie die Übung aus, während die KI Ihre Form analysiert",
    "demo.step4": "Feedback Erhalten",
    "demo.step4Desc": "Erhalten Sie Echtzeit-Korrektionen und Tipps zur Verbesserung Ihrer Form",
    "demo.step5": "Bericht Ansehen",
    "demo.step5Desc": "Sehen Sie eine detaillierte Analyse mit Scores, Winkeln und Verbesserungsbereichen",
    "demo.step6": "Fortschritt Verfolgen",
    "demo.step6Desc": "Überwachen Sie Ihre Verbesserungen im Laufe der Zeit im Dashboard",
    "demo.feature1": "Echtzeit-Analyse",
    "demo.feature1Desc": "Sofortiges Feedback zu Ihrer Form während des Trainings",
    "demo.feature2": "22 Übungen",
    "demo.feature2Desc": "Unterstützung für häufige Fitnessstudio-Übungen",
    "demo.feature3": "KI-Korrektionen",
    "demo.feature3Desc": "Intelligente Vorschläge zur Verletzungsprävention",
    "demo.feature4": "Fortschrittverfolgung",
    "demo.feature4Desc": "Überwachen Sie Ihre Verbesserungen im Laufe der Zeit",
    "demo.feature5": "Detaillierte Berichte",
    "demo.feature5Desc": "Umfassende Analyse mit Metriken",
    "demo.feature6": "Community-Chat",
    "demo.feature6Desc": "Verbinden Sie sich mit anderen Fitness-Enthusiasten",
    "exercise.barbellBicepsCurl": "Langhantel-Bizeps-Curl",
    "exercise.benchPress": "Bankdrücken",
    "exercise.chestFlyMachine": "Brustflugmaschine",
    "exercise.deadlift": "Kreuzheben",
    "exercise.declineBenchPress": "Negatives Bankdrücken",
    "exercise.hammerCurl": "Hammer-Curl",
    "exercise.hipThrust": "Hüftstoß",
    "exercise.inclineBenchPress": "Positives Bankdrücken",
    "exercise.latPulldown": "Latzug",
    "exercise.lateralRaise": "Seitenheben",
    "exercise.legExtension": "Beinstrecker",
    "exercise.legRaises": "Beinheben",
    "exercise.plank": "Planke",
    "exercise.pullUp": "Klimmzug",
    "exercise.pushUp": "Liegestütz",
    "exercise.romanianDeadlift": "Rumänisches Kreuzheben",
    "exercise.russianTwist": "Russische Drehung",
    "exercise.shoulderPress": "Schulterpresse",
    "exercise.squat": "Kniebeuge",
    "exercise.tBarRow": "T-Stangen-Rudern",
    "exercise.tricepPushdown": "Trizeps-Drücken",
    "exercise.tricepDips": "Trizeps-Dips",
  },
  zh: {
    "nav.home": "主页",
    "nav.demo": "演示",
    "nav.dashboard": "仪表板",
    "nav.analysis": "分析",
    "nav.settings": "设置",
    "home.title": "分析你的动作，提高你的表现",
    "home.subtitle": "AI驱动的分析，实时纠正",
    "home.startAnalysis": "开始分析",
    "home.demo": "演示",
    "home.progress": "你的进度",
    "home.sessions": "会话",
    "home.exercises": "练习",
    "home.score": "分数",
    "home.streak": "连续天数",
    "settings.account": "账户设置",
    "settings.subscription": "订阅",
    "settings.notifications": "通知",
    "settings.preferences": "偏好设置",
    "settings.darkMode": "深色模式",
    "settings.language": "语言",
    "settings.autoLanguage": "自动检测",
    "settings.voice": "语音",
    "settings.save": "保存",
    "settings.cancel": "取消",
    "dashboard.totalSessions": "总会话数",
    "dashboard.totalExercises": "总练习数",
    "dashboard.avgScore": "平均分数",
    "dashboard.currentStreak": "当前连胜",
    "dashboard.days": "天",
    "dashboard.recentAnalysis": "最近分析",
    "dashboard.noAnalysis": "还没有分析。开始您的第一次分析！",
    "demo.welcome": "欢迎来到 WazenAI",
    "demo.learnHow": "了解如何使用我们的智能健身分析系统",
    "demo.sixSteps": "6 个简单步骤",
    "demo.keyFeatures": "主要功能",
    "demo.exerciseDemos": "22 个练习演示",
    "demo.readyToStart": "准备好开始了吗？",
    "demo.experience": "体验实时 AI 驱动的健身分析",
    "demo.step1": "启用摄像头",
    "demo.step1Desc": "允许应用访问您的摄像头进行实时分析",
    "demo.step2": "选择练习",
    "demo.step2Desc": "从 22 种不同的练习中选择（深蹲、硬拉、卧推等）",
    "demo.step3": "执行动作",
    "demo.step3Desc": "在 AI 分析您的动作时执行练习",
    "demo.step4": "获取反馈",
    "demo.step4Desc": "获得实时纠正和改进动作的建议",
    "demo.step5": "查看报告",
    "demo.step5Desc": "查看包含分数、角度和改进区域的详细分析",
    "demo.step6": "跟踪进度",
    "demo.step6Desc": "在仪表板中监控您随时间的改进",
    "demo.feature1": "实时分析",
    "demo.feature1Desc": "在运动期间对您的动作进行即时反馈",
    "demo.feature2": "22 种练习",
    "demo.feature2Desc": "支持常见的健身房练习",
    "demo.feature3": "AI 纠正",
    "demo.feature3Desc": "防止受伤的智能建议",
    "demo.feature4": "进度跟踪",
    "demo.feature4Desc": "监控您随时间的改进",
    "demo.feature5": "详细报告",
    "demo.feature5Desc": "包含指标的综合分析",
    "demo.feature6": "社区聊天",
    "demo.feature6Desc": "与其他健身爱好者联系",
    "exercise.barbellBicepsCurl": "杠铃二头肌弯举",
    "exercise.benchPress": "卧推",
    "exercise.chestFlyMachine": "胸部飞鸟机",
    "exercise.deadlift": "硬拉",
    "exercise.declineBenchPress": "下斜卧推",
    "exercise.hammerCurl": "锤式弯举",
    "exercise.hipThrust": "臀推",
    "exercise.inclineBenchPress": "上斜卧推",
    "exercise.latPulldown": "背阔肌下拉",
    "exercise.lateralRaise": "侧平举",
    "exercise.legExtension": "腿部伸展",
    "exercise.legRaises": "腿部提升",
    "exercise.plank": "平板支撑",
    "exercise.pullUp": "引体向上",
    "exercise.pushUp": "俯卧撑",
    "exercise.romanianDeadlift": "罗马尼亚硬拉",
    "exercise.russianTwist": "俄罗斯转体",
    "exercise.shoulderPress": "肩部推举",
    "exercise.squat": "深蹲",
    "exercise.tBarRow": "T 杠划船",
    "exercise.tricepPushdown": "三头肌下压",
    "exercise.tricepDips": "三头肌浸没",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  autoDetect: boolean;
  setAutoDetect: (auto: boolean) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
  defaultLanguage?: Language;
}

export function LanguageProvider({
  children,
  defaultLanguage = "en",
}: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("language");
    return (stored as Language) || defaultLanguage;
  });

  const [autoDetect, setAutoDetect] = useState(() => {
    const stored = localStorage.getItem("autoLanguage");
    return stored ? JSON.parse(stored) : true;
  });

  useEffect(() => {
    if (autoDetect) {
      const browserLang = navigator.language.split("-")[0] as Language;
      const supportedLangs: Language[] = ["en", "ar", "es", "fr", "de", "zh"];
      if (supportedLangs.includes(browserLang)) {
        setLanguageState(browserLang);
        localStorage.setItem("language", browserLang);
      }
    }
  }, [autoDetect]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, autoDetect, setAutoDetect }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
